### PR TITLE
Check if props actually changed before reloading

### PR DESCRIPTION
**Pull request by heldinz**
This PR saves unnecessary reloading by comparing this.props and nextProps.

### CODE REVIEW

**Comment by minhtranite** [comment]
Thank for merge request.

**Comment by heldinz** [comment]
Thanks for merging so quickly! Any idea when you might be able to get a new release out?

**Comment by minhtranite** [comment]
https://github.com/vn38minhtran/react-lazysizes/releases/tag/v0.3.1

**Comment by heldinz** [comment]
Cheers :)

**Pull request merged**
